#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Any;
Perinci::CmdLine::Any->new(
    summary => 'Test command with multiple subcommands',
    subcommands  => {
        add      => {url => '/Perinci/Examples/Bin/Any/Multi/add'},
        subtract => {url => '/Perinci/Examples/Bin/Any/Multi/subtract'},
    },
)->run;

# ABSTRACT: 
# PODNAME:
